application:
    jwtExpirationMs: 864000000
    jwtSecret: ${SEC_JWT}

spring:
    datasource:
        password: ${DB_PASSWORD}
        url: ${DB_URL}
        username: ${DB_USER}

    jpa:
        hibernate:
            ddl-auto: ${DB_PERSIST}
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
    security:
        user:
            name: ${SEC_USERNAME}
            password: ${SEC_PASSWORD}

    sql:
        init:
            mode: always
            platform: postgres
